### ISSUE TITLE
Current implementations also clones functions in actions and fails

### ISSUE THREAD

**Issue by lunchspider** [Thunder-Solutions/Thunder-State#17]
To reproduce,
```
let state = createStore({
  name: 'Demo',
  state : { test : "test" },
  action : { helloWorld({state, payload}) {
    console.log("hello");
  }}
});
```
Error: 
![image](https://user-images.githubusercontent.com/35651798/218550657-1d38ff78-d8d0-43e9-bd4a-1c456d4813e5.png)

Possible fixes:
1. In deepClone function check if the values is a function and throw an error.
2. Don't clone actions in createStore.

**Comment by jonathandewitt-dev** [comment]
At first I was looking down rabbit holes trying to copy the methods to the new clone, but I was able to just avoid cloning objects expected to have methods, like `actions` and `computed`. Thanks for that suggestion, changed my mindset for the solution. Should be resolved in the latest commit.

NOTE: We might want some runtime type checking to make sure we give the user a more helpful error message, in case they try to add methods directly to the state.

**Comment by bcdewitt** [comment]
Would `Object.seal()` be what you're looking for, @jonathandewitt-dev?

**Comment by jonathandewitt-dev** [comment]
> Would `Object.seal()` be what you're looking for, @jonathandewitt-dev?

I'm not gonna say no absolutely, but my initial aversion is that seal creates a small side-effect; I hesitate to mutate the parameter. The mission of the cloning idea is to remove side effects.

**Comment by bcdewitt** [comment]
Ah, I guess if you did say you were avoiding cloning.

**Comment by bcdewitt** [comment]
If the actions are a flat list, you could potentially still clone via spread or `const newObj = Object.assign({}, actions)`, seal that new object and return it

**Comment by jonathandewitt-dev** [comment]
Sorry I think I misspoke a bit.

I was able to get around the problem by omitting actions and computed functions from the structuredClone, and I cloned them by using a shallow spread instead.

![Screenshot_20230213-222023.png](https://user-images.githubusercontent.com/55965128/218631003-a3ac734e-e0cc-44d6-ba1a-0bd4ff42db9c.png)

**Comment by jonathandewitt-dev** [comment]
For the sake of keeping helpful history, I'll fill in here. Took this offline, the one note we wanted to make here was adding a try/catch block around structuredClone, so we can control the error message and make it more helpful. Maybe suggest to check the state for functions that shouldnt be there, but keep it general and throw the original error.
