### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by jonathandewitt-dev** [Thunder-Solutions/Thunder-State#21]
Since I have an npm organization now, I can add more packages. Perhaps the main package can be `@thunder-state/core`, but I want to expose some integrations, like hooks for react for example. `@thunder-state/react` and `@thunder-state/vue` etc. Let's figure out what we need to do to make it convenient for everyone.

**Comment by veritem** [comment]
I find [pnpm](https://pnpm.io/) more convenient for doing this. I use it in a couple of places is like [here](https://github.com/veritem/eslint-config-veritem), and it also makes publishing easy. I would love to give help on this one if needed.

**Comment by jonathandewitt-dev** [comment]
The pnpm idea is great imo, good experience getting to know a better system than npm.  The speed difference for this package is probably negligible, but if it makes publishing easy, that could be a nice bonus.  I say go for it, if you want to convert to pnpm!

**Comment by jonathandewitt-dev** [comment]
Also, I think as discussed privately, the monorepo is possibly a better place to start than unit tests, because everything else may depend on that structure change.

**Comment by jonathandewitt-dev** [comment]
This has been closed with https://github.com/Thunder-Solutions/Thunder-State/pull/25
